### ISSUE TITLE
Error : Not an entity [class com.axelor.apps.base.db.Partner$ByteBuddy$zdDQYNGU]

### ISSUE THREAD

**Issue by AVR-David** [axelor/axelor-business-suite#1090]
Hi everyone,
I found an error in your code. so when i want create opportunity from partner or customer i have an error : 

> Error : Not an entity [class com.axelor.apps.base.db.Partner$ByteBuddy$zdDQYNGU]

in search, when i do the same thing with lead i haven't error.
So i found where is the problem.

Partner from axelor-crm 
```
<action-view` name="action-partner-view-create-opportunity" title="Create opportunity (${ fullName })" model="com.axelor.apps.crm.db.Opportunity">
    	<view type="form" name="opportunity-form"/>
    	<context name="_partner" expr="eval: __this__"/>
		<context name="_internalUserId" expr="eval: __user__.id"/>
    </action-view>
```

Lead from axelor-crm
 ```
<action-view name="action-lead-view-create-opportunity" title="Create opportunity (${ fullName })" model="com.axelor.apps.crm.db.Opportunity">
    	<view type="form" name="opportunity-form"/>
    	<context name="_lead" expr="eval: __self__"/>
    </action-view>
```

so when i chang in partner : 
`<context name="_partner" expr="eval: __this__"/>`
by : 
`<context name="_partner" expr="eval: __self__"/>`

this error disappears.
  
my company have access to 5.0.0 version.

**Comment by ale-axelor** [comment]
This issue happened because of the framework, it is now fixed in latest ADK version.

Both __this__ and __self__ are built-in variable that can be used here : 
__this__ is the record being edited (representing form values) and __self__ is the corresponding record from the database.
