### ISSUE TITLE
[dev] unable to add user

### ISSUE THREAD

**Issue by beuss** [axelor/axelor-business-suite#1837]
Trying to add user (both in dev & wip branches) results in a validation error "password cannot be null"

**Comment by beuss** [comment]
Password change does not work neither…

**Comment by gdu-axelor** [comment]
Strange, I can't reproduce. Create new user or change his password requires to enter the current user password for security.
This issue appears on a personalized user form view ?

**Comment by beuss** [comment]
nope default one, fresh install, new db

**Comment by beuss** [comment]
Screenshot of the issue

![image](https://user-images.githubusercontent.com/3670731/40223655-1012b80c-5a84-11e8-8153-8cf8663f2b83.png)

So I've only admin user, modifying the xhr to include the password field allows to create the user but password isn't properly encrypted then. Modifying password does not work at all neither from preferences form nor from admin edit

**Comment by gdu-axelor** [comment]
This view of user is a the old form view. Please take a look on this commit https://github.com/axelor/axelor-business-suite/commit/699caaf50663affe74081fd82a2db5449326a8ef#diff-278f685ae077b044de61d96efcff54a7 . Now you have to enter the current password of the connected user to update another password. This commit is pushed on master, dev and wip branches and RC2 release. I have checked, the password is correctly encrypted. The case you have seems be an use of recent ADK branch without recent ABS branch.

**Comment by beuss** [comment]
I had reset my branch to upstream/dev after fetch, strange.
Nevertheless this was a mismatch between ADK & the abs tree (ADK was out of date), updating adk & using wip on both fixed it.
Sorry for the noise and thank for the help (by the way, since you're around, can you have a look on #1761, #1628 and #1620?)
REgards
